/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { QuotaAccount, QuotaAccountRequest, QuotaExportDocument, QuotaExportRequest, QuotaResetStatsRequest, QuotaSetBalancesRequest, QuotaSnapshot, QuotaUsageReport, QuotaUsageRequest } from '@deepseek-ai/dsh-extension-quota-monitor/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$71756f74614d6f6e69746f72 {
    exportUsage: (request: QuotaExportRequest) => Promise<RemoteResult<QuotaExportDocument>>
    getAccount: (request: QuotaAccountRequest) => Promise<RemoteResult<QuotaAccount>>
    getSnapshot: () => Promise<RemoteResult<QuotaSnapshot>>
    getUsage: (request: QuotaUsageRequest) => Promise<RemoteResult<QuotaUsageReport>>
    resetStats: (request: QuotaResetStatsRequest) => Promise<RemoteResult<QuotaSnapshot>>
    setBalances: (request: QuotaSetBalancesRequest) => Promise<RemoteResult<Record<string, number>>>
  }
  interface TypertRemoteMap {
    'quotaMonitor/exportUsage': (request: QuotaExportRequest) => Promise<RemoteResult<QuotaExportDocument>>
    'quotaMonitor/getAccount': (request: QuotaAccountRequest) => Promise<RemoteResult<QuotaAccount>>
    'quotaMonitor/getSnapshot': () => Promise<RemoteResult<QuotaSnapshot>>
    'quotaMonitor/getUsage': (request: QuotaUsageRequest) => Promise<RemoteResult<QuotaUsageReport>>
    'quotaMonitor/resetStats': (request: QuotaResetStatsRequest) => Promise<RemoteResult<QuotaSnapshot>>
    'quotaMonitor/setBalances': (request: QuotaSetBalancesRequest) => Promise<RemoteResult<Record<string, number>>>
  }
  interface TypertRemoteNamespaceMap {
    'quotaMonitor': TypertRemoteNamespace$71756f74614d6f6e69746f72
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
