/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

let _deepseek_ai_dsh_extension_quota_monitor_quotaMonitor_exportUsage_parameter_0$schema$value
const _deepseek_ai_dsh_extension_quota_monitor_quotaMonitor_exportUsage_parameter_0$schema = () => (_deepseek_ai_dsh_extension_quota_monitor_quotaMonitor_exportUsage_parameter_0$schema$value ??= z.object({
  'kind': z.union([z.literal("daily-csv"), z.literal("sessions-csv"), z.literal("report-json")]),
}))
let _deepseek_ai_dsh_extension_quota_monitor_quotaMonitor_exportUsage_result$schema$value
const _deepseek_ai_dsh_extension_quota_monitor_quotaMonitor_exportUsage_result$schema = () => (_deepseek_ai_dsh_extension_quota_monitor_quotaMonitor_exportUsage_result$schema$value ??= z.object({
  'kind': z.union([z.literal("daily-csv"), z.literal("sessions-csv"), z.literal("report-json")]),
  'filename': z.string(),
  'mediaType': z.string(),
  'content': z.string(),
}))
let _deepseek_ai_dsh_extension_quota_monitor_quotaMonitor_getAccount_parameter_0$schema$value
const _deepseek_ai_dsh_extension_quota_monitor_quotaMonitor_getAccount_parameter_0$schema = () => (_deepseek_ai_dsh_extension_quota_monitor_quotaMonitor_getAccount_parameter_0$schema$value ??= z.object({
  'provider': z.string(),
  'refresh': z.boolean().optional(),
}))
let _deepseek_ai_dsh_extension_quota_monitor_quotaMonitor_getAccount_result$schema$value
const _deepseek_ai_dsh_extension_quota_monitor_quotaMonitor_getAccount_result$schema = () => (_deepseek_ai_dsh_extension_quota_monitor_quotaMonitor_getAccount_result$schema$value ??= z.object({
  'id': z.string().readonly(),
  'name': z.string(),
  'mode': z.union([z.literal("balance"), z.literal("subscription"), z.literal("unsupported")]),
  'status': z.union([z.literal("blocked"), z.literal("unsupported"), z.literal("ok"), z.literal("not-configured"), z.literal("unauthorized"), z.literal("rate-limited"), z.literal("invalid-response"), z.literal("unavailable")]),
  'adapter': z.string(),
  'fetchedAt': z.number(),
  'remaining': z.number().optional(),
  'used': z.number().optional(),
  'limit': z.number().optional(),
  'currency': z.string().optional(),
  'unlimited': z.boolean().optional(),
  'plan': z.string().optional(),
  'planWindows': z.array(z.object({
  'kind': z.union([z.literal("session"), z.literal("five-hour"), z.literal("daily"), z.literal("weekly"), z.literal("monthly"), z.literal("billing"), z.literal("quota")]),
  'percentUsed': z.number(),
  'resetAt': z.string().optional(),
  'remaining': z.number().optional(),
})).optional(),
  'budgetPools': z.array(z.object({
  'name': z.string(),
  'remaining': z.number(),
  'limit': z.number().optional(),
  'percentUsed': z.number().optional(),
})).optional(),
  'warning': z.union([z.literal("normal"), z.literal("warning"), z.literal("critical")]).optional(),
  'missingCredentials': z.array(z.string()).optional(),
  'reason': z.string().optional(),
  'manual': z.object({
  'total': z.number(),
  'spent': z.number(),
  'remaining': z.number(),
  'pct': z.number(),
}).optional(),
}))
let _deepseek_ai_dsh_extension_quota_monitor_quotaMonitor_getSnapshot_result$schema$value
const _deepseek_ai_dsh_extension_quota_monitor_quotaMonitor_getSnapshot_result$schema = () => (_deepseek_ai_dsh_extension_quota_monitor_quotaMonitor_getSnapshot_result$schema$value ??= z.object({
  'capturedAt': z.number(),
  'providers': z.array(z.object({
  'id': z.string().readonly(),
  'name': z.string(),
  'mode': z.union([z.literal("balance"), z.literal("subscription"), z.literal("unsupported")]),
  'adapter': z.string(),
  'status': z.union([z.literal("blocked"), z.literal("unsupported"), z.literal("ok"), z.literal("not-configured"), z.literal("unauthorized"), z.literal("rate-limited"), z.literal("invalid-response"), z.literal("unavailable")]),
  'warning': z.union([z.literal("normal"), z.literal("warning"), z.literal("critical")]).optional(),
})),
  'rows': z.array(z.object({
  'id': z.string().readonly(),
  'name': z.string(),
  'calls': z.number(),
  'inputTokens': z.number(),
  'outputTokens': z.number(),
  'cacheReadTokens': z.number(),
  'cacheWriteTokens': z.number(),
  'reasoningTokens': z.number(),
  'totalTokens': z.number(),
  'errorCount': z.number(),
  'lastCallAt': z.number(),
  'lastModel': z.string(),
  'balance': z.union([z.literal(null), z.object({
  'total': z.number(),
  'spent': z.number(),
  'remaining': z.number(),
  'pct': z.number(),
})]),
})),
  'balances': z.record(z.string(), z.number()),
  'aggregate': z.object({
  'calls': z.number(),
  'inputTokens': z.number(),
  'outputTokens': z.number(),
  'totalTokens': z.number(),
}),
}))
let _deepseek_ai_dsh_extension_quota_monitor_quotaMonitor_getUsage_parameter_0$schema$value
const _deepseek_ai_dsh_extension_quota_monitor_quotaMonitor_getUsage_parameter_0$schema = () => (_deepseek_ai_dsh_extension_quota_monitor_quotaMonitor_getUsage_parameter_0$schema$value ??= z.object({
  'refresh': z.boolean().optional(),
}))
let _deepseek_ai_dsh_extension_quota_monitor_quotaMonitor_getUsage_result$schema$value
const _deepseek_ai_dsh_extension_quota_monitor_quotaMonitor_getUsage_result$schema = () => (_deepseek_ai_dsh_extension_quota_monitor_quotaMonitor_getUsage_result$schema$value ??= z.object({
  'today': z.string(),
  'todayTotals': z.object({
  'inputTokens': z.number(),
  'outputTokens': z.number(),
  'cacheReadTokens': z.number(),
  'cacheWriteTokens': z.number(),
  'totalTokens': z.number(),
}),
  'monthTotals': z.object({
  'inputTokens': z.number(),
  'outputTokens': z.number(),
  'cacheReadTokens': z.number(),
  'cacheWriteTokens': z.number(),
  'totalTokens': z.number(),
}),
  'allTimeTotals': z.object({
  'inputTokens': z.number(),
  'outputTokens': z.number(),
  'cacheReadTokens': z.number(),
  'cacheWriteTokens': z.number(),
  'totalTokens': z.number(),
}),
  'todayCost': z.object({
  'amount': z.number(),
  'currency': z.string(),
  'unpricedCalls': z.number(),
}).optional(),
  'monthCost': z.object({
  'amount': z.number(),
  'currency': z.string(),
  'unpricedCalls': z.number(),
}).optional(),
  'allTimeCost': z.object({
  'amount': z.number(),
  'currency': z.string(),
  'unpricedCalls': z.number(),
}).optional(),
  'budgets': z.object({
  'currency': z.string(),
  'daily': z.object({
  'limit': z.number(),
  'spent': z.number(),
  'percentUsed': z.number(),
  'status': z.union([z.literal("normal"), z.literal("warning"), z.literal("critical"), z.literal("unknown")]),
  'unpricedCalls': z.number(),
}).optional(),
  'monthly': z.object({
  'limit': z.number(),
  'spent': z.number(),
  'percentUsed': z.number(),
  'status': z.union([z.literal("normal"), z.literal("warning"), z.literal("critical"), z.literal("unknown")]),
  'unpricedCalls': z.number(),
}).optional(),
}).optional(),
  'todayCacheHitPercent': z.number().optional(),
  'days': z.array(z.object({
  'date': z.string().readonly(),
  'calls': z.number(),
  'models': z.array(z.object({
  'provider': z.string().readonly(),
  'model': z.string().readonly(),
  'calls': z.number(),
  'cost': z.object({
  'amount': z.number(),
  'currency': z.string(),
  'unpricedCalls': z.number(),
}).optional(),
  'inputTokens': z.number(),
  'outputTokens': z.number(),
  'cacheReadTokens': z.number(),
  'cacheWriteTokens': z.number(),
  'totalTokens': z.number(),
})),
  'cost': z.object({
  'amount': z.number(),
  'currency': z.string(),
  'unpricedCalls': z.number(),
}).optional(),
  'inputTokens': z.number(),
  'outputTokens': z.number(),
  'cacheReadTokens': z.number(),
  'cacheWriteTokens': z.number(),
  'totalTokens': z.number(),
})),
  'sessions': z.array(z.object({
  'id': z.string().readonly(),
  'calls': z.number(),
  'routes': z.array(z.string()),
  'lastActiveAt': z.number(),
  'cost': z.object({
  'amount': z.number(),
  'currency': z.string(),
  'unpricedCalls': z.number(),
}).optional(),
  'inputTokens': z.number(),
  'outputTokens': z.number(),
  'cacheReadTokens': z.number(),
  'cacheWriteTokens': z.number(),
  'totalTokens': z.number(),
})),
  'sessionCount': z.number(),
  'foldedAt': z.number(),
  'folding': z.boolean(),
}))
let _deepseek_ai_dsh_extension_quota_monitor_quotaMonitor_resetStats_parameter_0$schema$value
const _deepseek_ai_dsh_extension_quota_monitor_quotaMonitor_resetStats_parameter_0$schema = () => (_deepseek_ai_dsh_extension_quota_monitor_quotaMonitor_resetStats_parameter_0$schema$value ??= z.object({
  'provider': z.union([z.undefined(), z.string()]).optional(),
}))
let _deepseek_ai_dsh_extension_quota_monitor_quotaMonitor_resetStats_result$schema$value
const _deepseek_ai_dsh_extension_quota_monitor_quotaMonitor_resetStats_result$schema = () => (_deepseek_ai_dsh_extension_quota_monitor_quotaMonitor_resetStats_result$schema$value ??= z.object({
  'capturedAt': z.number(),
  'providers': z.array(z.object({
  'id': z.string().readonly(),
  'name': z.string(),
  'mode': z.union([z.literal("balance"), z.literal("subscription"), z.literal("unsupported")]),
  'adapter': z.string(),
  'status': z.union([z.literal("blocked"), z.literal("unsupported"), z.literal("ok"), z.literal("not-configured"), z.literal("unauthorized"), z.literal("rate-limited"), z.literal("invalid-response"), z.literal("unavailable")]),
  'warning': z.union([z.literal("normal"), z.literal("warning"), z.literal("critical")]).optional(),
})),
  'rows': z.array(z.object({
  'id': z.string().readonly(),
  'name': z.string(),
  'calls': z.number(),
  'inputTokens': z.number(),
  'outputTokens': z.number(),
  'cacheReadTokens': z.number(),
  'cacheWriteTokens': z.number(),
  'reasoningTokens': z.number(),
  'totalTokens': z.number(),
  'errorCount': z.number(),
  'lastCallAt': z.number(),
  'lastModel': z.string(),
  'balance': z.union([z.literal(null), z.object({
  'total': z.number(),
  'spent': z.number(),
  'remaining': z.number(),
  'pct': z.number(),
})]),
})),
  'balances': z.record(z.string(), z.number()),
  'aggregate': z.object({
  'calls': z.number(),
  'inputTokens': z.number(),
  'outputTokens': z.number(),
  'totalTokens': z.number(),
}),
}))
let _deepseek_ai_dsh_extension_quota_monitor_quotaMonitor_setBalances_parameter_0$schema$value
const _deepseek_ai_dsh_extension_quota_monitor_quotaMonitor_setBalances_parameter_0$schema = () => (_deepseek_ai_dsh_extension_quota_monitor_quotaMonitor_setBalances_parameter_0$schema$value ??= z.object({
  'balances': z.record(z.string(), z.number()),
}))
let _deepseek_ai_dsh_extension_quota_monitor_quotaMonitor_setBalances_result$schema$value
const _deepseek_ai_dsh_extension_quota_monitor_quotaMonitor_setBalances_result$schema = () => (_deepseek_ai_dsh_extension_quota_monitor_quotaMonitor_setBalances_result$schema$value ??= z.record(z.string(), z.number()))

export const TYPERT = {
  package: '@deepseek-ai/dsh-extension-quota-monitor',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@deepseek-ai/dsh-extension-quota-monitor#quotaMonitor/exportUsage',
      service: 'quotaMonitor',
      namespace: 'quotaMonitor',
      method: 'exportUsage',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-extension-quota-monitor/types#QuotaExportRequest',
            create: _deepseek_ai_dsh_extension_quota_monitor_quotaMonitor_exportUsage_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-extension-quota-monitor/types#QuotaExportDocument',
        create: _deepseek_ai_dsh_extension_quota_monitor_quotaMonitor_exportUsage_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/extension-quota-monitor/src/index.ts","line":223,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-extension-quota-monitor#quotaMonitor/getAccount',
      service: 'quotaMonitor',
      namespace: 'quotaMonitor',
      method: 'getAccount',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-extension-quota-monitor/types#QuotaAccountRequest',
            create: _deepseek_ai_dsh_extension_quota_monitor_quotaMonitor_getAccount_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-extension-quota-monitor/types#QuotaAccount',
        create: _deepseek_ai_dsh_extension_quota_monitor_quotaMonitor_getAccount_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/extension-quota-monitor/src/index.ts","line":199,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-extension-quota-monitor#quotaMonitor/getSnapshot',
      service: 'quotaMonitor',
      namespace: 'quotaMonitor',
      method: 'getSnapshot',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-extension-quota-monitor/types#QuotaSnapshot',
        create: _deepseek_ai_dsh_extension_quota_monitor_quotaMonitor_getSnapshot_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/extension-quota-monitor/src/index.ts","line":189,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-extension-quota-monitor#quotaMonitor/getUsage',
      service: 'quotaMonitor',
      namespace: 'quotaMonitor',
      method: 'getUsage',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-extension-quota-monitor/types#QuotaUsageRequest',
            create: _deepseek_ai_dsh_extension_quota_monitor_quotaMonitor_getUsage_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-extension-quota-monitor/types#QuotaUsageReport',
        create: _deepseek_ai_dsh_extension_quota_monitor_quotaMonitor_getUsage_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/extension-quota-monitor/src/index.ts","line":212,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-extension-quota-monitor#quotaMonitor/resetStats',
      service: 'quotaMonitor',
      namespace: 'quotaMonitor',
      method: 'resetStats',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-extension-quota-monitor/types#QuotaResetStatsRequest',
            create: _deepseek_ai_dsh_extension_quota_monitor_quotaMonitor_resetStats_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-extension-quota-monitor/types#QuotaSnapshot',
        create: _deepseek_ai_dsh_extension_quota_monitor_quotaMonitor_resetStats_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/extension-quota-monitor/src/index.ts","line":248,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-extension-quota-monitor#quotaMonitor/setBalances',
      service: 'quotaMonitor',
      namespace: 'quotaMonitor',
      method: 'setBalances',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-extension-quota-monitor/types#QuotaSetBalancesRequest',
            create: _deepseek_ai_dsh_extension_quota_monitor_quotaMonitor_setBalances_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-extension-quota-monitor#quotaMonitor/setBalances:result',
        create: _deepseek_ai_dsh_extension_quota_monitor_quotaMonitor_setBalances_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/extension-quota-monitor/src/index.ts","line":233,"column":3},
    },
  ],
  model: {
    "services": [
      {
        "description": "Token usage plus account monitoring for every configured LLM provider. Serves the browser panel through the Gateway as the `quotaMonitor` namespace.",
        "summary": "Token usage plus account monitoring for every configured LLM provider.",
        "tags": [],
        "jsDoc": "/**\n * Token usage plus account monitoring for every configured LLM provider.\n * Serves the browser panel through the Gateway as the `quotaMonitor`\n * namespace.\n */",
        "key": "quotaMonitor",
        "exportName": "QuotaMonitorService",
        "members": [
          {
            "kind": "method",
            "name": "getSnapshot",
            "signature": "@Remote('getSnapshot') getSnapshot(): QuotaSnapshot",
            "summary": "Whole-registry view: the provider selector, per-process usage rows, and the manual balance table.",
            "jsDoc": "/**\n * Whole-registry view: the provider selector, per-process usage rows, and\n * the manual balance table.\n * @returns the snapshot served to the panel.\n */"
          },
          {
            "kind": "method",
            "name": "getAccount",
            "signature": "@Remote('getAccount') async getAccount(request: QuotaAccountRequest): Promise<QuotaAccount>",
            "summary": "Read one provider's account.",
            "jsDoc": "/**\n * Read one provider's account.\n * @param request - the provider and whether to bypass the cached reading.\n * @returns the account, including a non-`ok` status when it cannot be read.\n */"
          },
          {
            "kind": "method",
            "name": "getUsage",
            "signature": "@Remote('getUsage') async getUsage(request: QuotaUsageRequest): Promise<QuotaUsageReport>",
            "summary": "The folded historical usage report.",
            "jsDoc": "/**\n * The folded historical usage report.\n * @param request - `refresh: true` forces a fold round before answering.\n * @returns the report, with `folding` set while a round runs.\n */"
          },
          {
            "kind": "method",
            "name": "exportUsage",
            "signature": "@Remote('exportUsage') exportUsage(request: QuotaExportRequest): QuotaExportDocument",
            "summary": "Build one downloadable document from the current report.",
            "jsDoc": "/**\n * Build one downloadable document from the current report.\n * @param request - which document to build.\n * @returns the document, with its filename and media type.\n */"
          },
          {
            "kind": "method",
            "name": "setBalances",
            "signature": "@Remote('setBalances') setBalances(request: QuotaSetBalancesRequest): Record<string, number>",
            "summary": "Replace the manual balance fallbacks.",
            "jsDoc": "/**\n * Replace the manual balance fallbacks.\n * @param request - provider id → total allowance; a non-finite value clears the entry.\n * @returns the resulting manual balance table.\n */"
          },
          {
            "kind": "method",
            "name": "resetStats",
            "signature": "@Remote('resetStats') resetStats(request: QuotaResetStatsRequest): QuotaSnapshot",
            "summary": "Zero the per-process usage counters.",
            "jsDoc": "/**\n * Zero the per-process usage counters.\n * @param request - restrict the reset to one provider route, or clear every bucket.\n * @returns the post-reset snapshot.\n */"
          }
        ],
        "types": [
          {
            "name": "QuotaAccount",
            "declaration": "export interface QuotaAccount {\n    readonly id: string;\n    name: string;\n    mode: QuotaAccountMode;\n    status: QuotaAccountStatus;\n    adapter: string;\n    fetchedAt: number;\n    remaining?: number;\n    used?: number;\n    limit?: number;\n    currency?: string;\n    unlimited?: boolean;\n    plan?: string;\n    planWindows?: readonly QuotaPlanWindow[];\n    budgetPools?: readonly QuotaBudgetPool[];\n    warning?: QuotaWarningLevel;\n    missingCredentials?: readonly string[];\n    reason?: string;\n    manual?: QuotaBalanceEstimate;\n}"
          },
          {
            "name": "QuotaAccountMode",
            "declaration": "export type QuotaAccountMode = 'balance' | 'subscription' | 'unsupported';"
          },
          {
            "name": "QuotaAccountRequest",
            "declaration": "export interface QuotaAccountRequest {\n    provider: string;\n    refresh?: boolean;\n}"
          },
          {
            "name": "QuotaAccountStatus",
            "declaration": "export type QuotaAccountStatus = 'ok' | 'not-configured' | 'unauthorized' | 'rate-limited' | 'unsupported' | 'invalid-response' | 'blocked' | 'unavailable';"
          },
          {
            "name": "QuotaBalanceEstimate",
            "declaration": "export interface QuotaBalanceEstimate {\n    total: number;\n    spent: number;\n    remaining: number;\n    pct: number;\n}"
          },
          {
            "name": "QuotaBudgetPool",
            "declaration": "export interface QuotaBudgetPool {\n    name: string;\n    remaining: number;\n    limit?: number;\n    percentUsed?: number;\n}"
          },
          {
            "name": "QuotaBudgetStatus",
            "declaration": "export type QuotaBudgetStatus = 'normal' | 'warning' | 'critical' | 'unknown';"
          },
          {
            "name": "QuotaBudgetView",
            "declaration": "export interface QuotaBudgetView {\n    currency: string;\n    daily?: QuotaBudgetWindow;\n    monthly?: QuotaBudgetWindow;\n}"
          },
          {
            "name": "QuotaBudgetWindow",
            "declaration": "export interface QuotaBudgetWindow {\n    limit: number;\n    spent: number;\n    percentUsed: number;\n    status: QuotaBudgetStatus;\n    unpricedCalls: number;\n}"
          },
          {
            "name": "QuotaCostView",
            "declaration": "export interface QuotaCostView {\n    amount: number;\n    currency: string;\n    unpricedCalls: number;\n}"
          },
          {
            "name": "QuotaDayUsage",
            "declaration": "export interface QuotaDayUsage extends QuotaTokenTotals {\n    readonly date: string;\n    calls: number;\n    models: readonly QuotaModelUsage[];\n    cost?: QuotaCostView;\n}"
          },
          {
            "name": "QuotaExportDocument",
            "declaration": "export interface QuotaExportDocument {\n    kind: QuotaExportKind;\n    filename: string;\n    mediaType: string;\n    content: string;\n}"
          },
          {
            "name": "QuotaExportKind",
            "declaration": "export type QuotaExportKind = 'daily-csv' | 'sessions-csv' | 'report-json';"
          },
          {
            "name": "QuotaExportRequest",
            "declaration": "export interface QuotaExportRequest {\n    kind: QuotaExportKind;\n}"
          },
          {
            "name": "QuotaModelUsage",
            "declaration": "export interface QuotaModelUsage extends QuotaTokenTotals {\n    readonly provider: string;\n    readonly model: string;\n    calls: number;\n    cost?: QuotaCostView;\n}"
          },
          {
            "name": "QuotaPlanWindow",
            "declaration": "export interface QuotaPlanWindow {\n    kind: QuotaPlanWindowKind;\n    percentUsed: number;\n    resetAt?: string;\n    remaining?: number;\n}"
          },
          {
            "name": "QuotaPlanWindowKind",
            "declaration": "export type QuotaPlanWindowKind = 'session' | 'five-hour' | 'daily' | 'weekly' | 'monthly' | 'billing' | 'quota';"
          },
          {
            "name": "QuotaProviderEntry",
            "declaration": "export interface QuotaProviderEntry {\n    readonly id: string;\n    name: string;\n    mode: QuotaAccountMode;\n    adapter: string;\n    status: QuotaAccountStatus;\n    warning?: QuotaWarningLevel;\n}"
          },
          {
            "name": "QuotaProviderRow",
            "declaration": "export interface QuotaProviderRow {\n    readonly id: string;\n    name: string;\n    calls: number;\n    inputTokens: number;\n    outputTokens: number;\n    cacheReadTokens: number;\n    cacheWriteTokens: number;\n    reasoningTokens: number;\n    totalTokens: number;\n    errorCount: number;\n    lastCallAt: number;\n    lastModel: string;\n    balance: QuotaBalanceEstimate | null;\n}"
          },
          {
            "name": "QuotaResetStatsRequest",
            "declaration": "export interface QuotaResetStatsRequest {\n    provider?: string | undefined;\n}"
          },
          {
            "name": "QuotaSessionUsage",
            "declaration": "export interface QuotaSessionUsage extends QuotaTokenTotals {\n    readonly id: string;\n    calls: number;\n    routes: readonly string[];\n    lastActiveAt: number;\n    cost?: QuotaCostView;\n}"
          },
          {
            "name": "QuotaSetBalancesRequest",
            "declaration": "export interface QuotaSetBalancesRequest {\n    balances: Record<string, number>;\n}"
          },
          {
            "name": "QuotaSnapshot",
            "declaration": "export interface QuotaSnapshot {\n    capturedAt: number;\n    providers: readonly QuotaProviderEntry[];\n    rows: readonly QuotaProviderRow[];\n    balances: Record<string, number>;\n    aggregate: { calls: number; inputTokens: number; outputTokens: number; totalTokens: number; };\n}"
          },
          {
            "name": "QuotaTokenTotals",
            "declaration": "export interface QuotaTokenTotals {\n    inputTokens: number;\n    outputTokens: number;\n    cacheReadTokens: number;\n    cacheWriteTokens: number;\n    totalTokens: number;\n}"
          },
          {
            "name": "QuotaUsageReport",
            "declaration": "export interface QuotaUsageReport {\n    today: string;\n    todayTotals: QuotaTokenTotals;\n    monthTotals: QuotaTokenTotals;\n    allTimeTotals: QuotaTokenTotals;\n    todayCost?: QuotaCostView;\n    monthCost?: QuotaCostView;\n    allTimeCost?: QuotaCostView;\n    budgets?: QuotaBudgetView;\n    todayCacheHitPercent?: number;\n    days: readonly QuotaDayUsage[];\n    sessions: readonly QuotaSessionUsage[];\n    sessionCount: number;\n    foldedAt: number;\n    folding: boolean;\n}"
          },
          {
            "name": "QuotaUsageRequest",
            "declaration": "export interface QuotaUsageRequest {\n    refresh?: boolean;\n}"
          },
          {
            "name": "QuotaWarningLevel",
            "declaration": "export type QuotaWarningLevel = 'normal' | 'warning' | 'critical';"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
